### ISSUE TITLE
Update the npm repo with new version

### ISSUE THREAD

**Issue by limikael** [juicesharp/ftpUploadTask#2]
Hi,

Can you please bump the version and publish it to the npm repo? Alternatively give me access to it so I can do it...

**Comment by juicesharp** [comment]
Hi.

Added you as collaborator there as well.

From: Mikael Lindqvist
Sent: ‎Wednesday‎, ‎June‎ ‎10‎, ‎2015 ‎6‎:‎51‎ ‎AM
To: juicesharp/ftpUploadTask

Hi,

Can you please bump the version and publish it to the npm repo? Alternatively give me access to it so I can do it...

**Comment by limikael** [comment]
Awesome! v 0.1.2 released! :)

https://www.npmjs.com/package/grunt-ftpuploadtask
